FROM node:alpine
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"

RUN apk --no-cache upgrade && \
    apk --no-cache add \
    curl

HEALTHCHECK --interval=15s --timeout=15s \
 CMD curl --silent --fail http://localhost:5000/ || exit 1

WORKDIR /ui_src

RUN npm i npm@latest -g

EXPOSE 5000
CMD npm ci --no-optional && npm start